name: alex
description: "Aplicao para gerenciar horas de caminhoneiros"

publish_to: 'br.com.pioriam'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  intl: ^0.20.2
  mask_text_input_formatter: ^2.9.0
  flutter_launcher_icons: ^0.14.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icon/
